import { describe } from 'vitest';
import { engrave, forge } from './index.js';

// `deny` disallow features, either:
//  - outright, like indented code block and setext headings
//  - partially, like entities allowed in numeric form and not HTML5 named, or
//  - stricter rules, like block quotes requiring '>' at the start of every line
describe('spec', ({ concurrent: it }) => {
	// https://spec.commonmark.org/0.31.2/
	const suite: Record<string, [input: string, output: string]> = {
		'001|deny': ['\tfoo\tbaz\t\tbim', '<p>foo\tbaz\t\tbim</p>'],
		'002|deny': ['  \tfoo\tbaz\t\tbim', '<p>foo\tbaz\t\tbim</p>'],
		'003|deny': ['    a\ta\n    ὐ\ta', '<p>a\ta\nὐ\ta</p>'],
		'004': ['  - foo\n\n\tbar', '<ul>\n<li>\n<p>foo</p>\n<p>bar</p>\n</li>\n</ul>'],
		'005': ['- foo\n\n\t\tbar', '<ul>\n<li>\n<p>foo</p>\n<p>bar</p>\n</li>\n</ul>'],
		'006|deny': ['>\t\tfoo', '<blockquote>\n<p>foo</p>\n</blockquote>'],
		'007|deny': ['-\t\tfoo', '<ul>\n<li>foo</li>\n</ul>'],
		'008|deny': ['    foo\n\tbar', '<p>foo\nbar</p>'],
		'009|todo': [
			' - foo\n   - bar\n\t - baz',
			'<ul>\n<li>foo\n<ul>\n<li>bar\n<ul>\n<li>baz</li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>',
		],
		'010|plus': ['#\tFoo', '<h1 id="foo">Foo</h1>'],
		'011': ['*\t*\t*\t', '<hr />'],
		'012': [
			'\\!\\"\\#\\$\\%\\&\\\'\\(\\)\\*\\+\\,\\-\\.\\/\\:\\;\\<\\=\\>\\?\\@\\[\\\\\\]\\^\\_\\`\\{\\|\\}\\~',
			"<p>!&quot;#$%&amp;'()*+,-./:;&lt;=&gt;?@[\\]^_`{|}~</p>",
		],
		'013': ['\\→\\A\\a\\ \\3\\φ\\«', '<p>\\→\\A\\a\\ \\3\\φ\\«</p>'],
		'014': [
			[
				'\\*not emphasized*',
				'\\<br/> not a tag',
				'\\[not a link](/foo)',
				'\\`not code`',
				'1\\. not a list',
				'\\* not a list',
				'\\# not a heading',
				'\\[foo]: /url "not a reference"',
				'\\&ouml; not a character entity',
			].join('\n'),
			[
				'<p>*not emphasized*',
				'&lt;br/&gt; not a tag',
				'[not a link](/foo)',
				'`not code`',
				'1. not a list',
				'* not a list',
				'# not a heading',
				'[foo]: /url &quot;not a reference&quot;',
				'&amp;ouml; not a character entity</p>',
			].join('\n'),
		],
		'015': ['\\\\*emphasis*', '<p>\\<em>emphasis</em></p>'],
		'016': ['foo\\\nbar', '<p>foo<br />\nbar</p>'],
		'017': ['`` \\[\\` ``', '<p><code>\\[\\`</code></p>'],
		'018|deny': ['    \[\]', '<p>\[\]</p>'],
		'019': ['~~~\n\\[\\]\n~~~', '<pre><code>\\[\\]\n</code></pre>'],
		'020': [
			'<https://example.com?find=\\*>',
			'<p><a href="https://example.com?find=%5C*">https://example.com?find=\\*</a></p>',
		],
		'021|deny': ['<a href="/bar\\/)"></a>', '<a href="/bar\\/)"></a>'],
		'022': ['[foo](/bar\\* "ti\\*tle")', '<p><a href="/bar*" title="ti*tle">foo</a></p>'],
		'023|skip': [
			'[foo]\n\n[foo]: /bar\\* "ti\\*tle"',
			'<p><a href="/bar*" title="ti*tle">foo</a></p>',
		],
		'024|mod': ['``` foo\+bar\nfoo\n```', '<pre data-language="foo+bar"><code>foo\n</code></pre>'],
		'025|deny': [
			'&nbsp; &amp; &copy; &AElig; &Dcaron;\n&frac34; &HilbertSpace; &DifferentialD;\n&ClockwiseContourIntegral; &ngE;',
			'<p>&nbsp; &amp; &copy; &AElig; &Dcaron;\n&frac34; &HilbertSpace; &DifferentialD;\n&ClockwiseContourIntegral; &ngE;</p>',
		],
		'026': ['&#35; &#1234; &#992; &#0;', '<p># Ӓ Ϡ �</p>'],
		'027': ['&#X22; &#XD06; &#xcab;', '<p>&quot; ആ ಫ</p>'],
		'028|skip': [
			'&nbsp &x; &#; &#x;\n&#87654321;\n&#abcdef0;\n&ThisIsNotDefined; &hi?;',
			'<p>&amp;nbsp &amp;x; &amp;#; &amp;#x;\n&amp;#87654321;\n&amp;#abcdef0;\n&amp;ThisIsNotDefined; &amp;hi?;</p>',
		],
		'029': ['&copy', '<p>&amp;copy</p>'],
		'030|skip': ['&MadeUpEntity;', '<p>&amp;MadeUpEntity;</p>'],
		'031|deny': ['<a href="&ouml;&ouml;.html"></a>', '<a href="&ouml;&ouml;.html"></a>'],
		'032|todo': [
			'[foo](/f&ouml;&ouml; "f&ouml;&ouml;")',
			'<p><a href="/f%C3%B6%C3%B6" title="föö">foo</a></p>',
		],
		'033|skip': [
			'[foo]\n\n[foo]: /f&ouml;&ouml; "f&ouml;&ouml;"',
			'<p><a href="/f%C3%B6%C3%B6" title="föö">foo</a></p>',
		],
		'034|skip': ['``` f&ouml;&ouml;\nfoo\n```', '<pre data-language="föö"><code>foo</code></pre>'],
		'035': ['`f&ouml;&ouml;`', '<p><code>f&amp;ouml;&amp;ouml;</code></p>'],
		'036|mod': ['```\nf&ouml;f&ouml;\n```', '<pre><code>f&amp;ouml;f&amp;ouml;\n</code></pre>'],
		'037': ['&#42;foo&#42;\n*foo*', '<p>*foo*\n<em>foo</em></p>'],
		'038': ['&#42; foo\n\n* foo', '<p>* foo</p>\n<ul>\n<li>foo</li>\n</ul>'],
		'039': ['foo&#10;&#10;bar', '<p>foo\n\nbar</p>'],
		'040': ['&#9;foo', '<p>\tfoo</p>'],
		'041': ['[a](url &quot;tit&quot;)', '<p>[a](url &quot;tit&quot;)</p>'],
		'042': ['- `one\n- two`', '<ul>\n<li>`one</li>\n<li>two`</li>\n</ul>'],
		'043': ['***\n---\n___', '<hr />\n<hr />\n<hr />'],
		'044': ['+++', '<p>+++</p>'],
		'045': ['===', '<p>===</p>'],
		'046': ['**\n--\n__', '<p>**\n--\n__</p>'],
		'047': [' ***\n  ***\n   ***', '<hr />\n<hr />\n<hr />'],
		'048|deny': ['    ***', '<hr />'],
		'049|deny': ['Foo\n    ***', '<p>Foo</p>\n<hr />'],
		'050|': ['_____________________________________', '<hr />'],
		'051': [' - - -', '<hr />'],
		'052': [' **  * ** * ** * **', '<hr />'],
		'053': ['-     -      -      -', '<hr />'],
		'054': ['- - - -    ', '<hr />'],
		'055': [' ***\n  ***\n   ***', '<hr />\n<hr />\n<hr />'],
		'056': [' *-*', '<p><em>-</em></p>'],
		'057': ['- foo\n***\n- bar', '<ul>\n<li>foo</li>\n</ul>\n<hr />\n<ul>\n<li>bar</li>\n</ul>'],
		'058': ['foo\n***\nbar', '<p>foo</p>\n<hr />\n<p>bar</p>'],
		'059|deny': ['Foo\n---\nbar', '<p>Foo</p>\n<hr />\n<p>bar</p>'],
		'060': ['* Foo\n* * *\n* Bar', '<ul>\n<li>Foo</li>\n</ul>\n<hr />\n<ul>\n<li>Bar</li>\n</ul>'],
		'061': ['- Foo\n- * * *', '<ul>\n<li>Foo</li>\n<li>\n<hr />\n</li>\n</ul>'],
		'062|plus': [
			'# foo\n## foo\n### foo\n#### foo\n##### foo\n###### foo',
			[
				'<h1 id="foo">foo</h1>',
				`<h2 id="${Array(2).fill('foo').join('-')}">foo</h2>`,
				`<h3 id="${Array(3).fill('foo').join('-')}">foo</h3>`,
				`<h4 id="${Array(4).fill('foo').join('-')}">foo</h4>`,
				`<h5 id="${Array(5).fill('foo').join('-')}">foo</h5>`,
				`<h6 id="${Array(6).fill('foo').join('-')}">foo</h6>`,
			].join('\n'),
		],
		'063': ['####### foo', '<p>####### foo</p>'],
		'064': ['#5 bolt\n\n#hashtag', '<p>#5 bolt</p>\n<p>#hashtag</p>'],
		'065': ['\\## foo', '<p>## foo</p>'],
		'066|plus': ['# foo *bar* \\*baz\\*', '<h1 id="foo-bar-baz">foo <em>bar</em> *baz*</h1>'],
		'067|plus': ['#                  foo                     ', '<h1 id="foo">foo</h1>'],
		'068|plus': [
			' ### foo\n  ## foo\n   # foo',
			['<h3 id="foo">foo</h3>', '<h2 id="foo-1">foo</h2>', '<h1 id="foo-2">foo</h1>'].join('\n'),
		],
		'069|deny': ['    # foo', '<h1 id="foo">foo</h1>'],
		'070|deny': ['foo\n    # bar', '<p>foo</p>\n<h1 id="bar">bar</h1>'],
		'071|deny': [
			'## foo ##\n  ###   bar    ###',
			['<h2 id="foo">foo ##</h2>', '<h3 id="foo-bar">bar    ###</h3>'].join('\n'),
		],
		'072|deny': [
			'# foo ##################################\n##### foo ##',
			[
				'<h1 id="foo">foo ##################################</h1>',
				'<h5 id="foo-foo">foo ##</h5>',
			].join('\n'),
		],
		'073|deny': ['### foo ###     ', '<h3 id="foo">foo ###</h3>'],
		'074|plus': ['### foo ### b', '<h3 id="foo-b">foo ### b</h3>'],
		'075|plus': ['# foo#', '<h1 id="foo">foo#</h1>'],
		'076|deny': [
			'### foo \\###\n## foo #\\##\n# foo \\#',
			[
				'<h3 id="foo">foo ###</h3>',
				'<h2 id="foo-1">foo ###</h2>',
				'<h1 id="foo-2">foo #</h1>',
			].join('\n'),
		],
		'077|deny': ['****\n## foo\n****', '<hr />\n<h2 id="foo">foo</h2>\n<hr />'],
		'078|plus': [
			'Foo bar\n# baz\nBar foo',
			'<p>Foo bar</p>\n<h1 id="baz">baz</h1>\n<p>Bar foo</p>',
		],
		'079|deny': ['## \n#\n### ###', '<p>##\n#</p>\n<h3>###</h3>'],
		'080|deny': [
			'Foo *bar*\n=========\n\nFoo *bar*\n---------',
			'<p>Foo <em>bar</em>\n=========</p>\n<p>Foo <em>bar</em></p>\n<hr />',
		],
		'081|deny': ['Foo *bar\nbaz*\n====', '<p>Foo <em>bar\nbaz</em>\n====</p>'],
		'082|deny': ['Foo *bar\nbaz*\t\n====', '<p>Foo <em>bar\nbaz</em>\n====</p>'],
		'083|deny': ['Foo\n-------------------------\n\nFoo\n=', '<p>Foo</p>\n<hr />\n<p>Foo\n=</p>'],
		'084|deny': [
			'   Foo\n---\n\n  Foo\n-----\n\n  Foo\n  ===',
			'<p>Foo</p>\n<hr />\n<p>Foo</p>\n<hr />\n<p>Foo\n===</p>',
		],
		'085|deny': ['    Foo\n    ---\n\n    Foo\n---', '<p>Foo</p>\n<hr />\n<p>Foo</p>\n<hr />'],
		'086|deny': ['Foo\n   ----      ', '<p>Foo</p>\n<hr />'],
		'087|deny': ['Foo\n    ---', '<p>Foo</p>\n<hr />'],
		'088': ['Foo\n= =\n\nFoo\n--- -', '<p>Foo\n= =</p>\n<p>Foo</p>\n<hr />'],
		'089|deny': ['Foo  \n-----', '<p>Foo</p>\n<hr />'],
		'090|deny': ['Foo\\\n----', '<p>Foo\\</p>\n<hr />'],
		'091|deny': [
			'`Foo\n----\n`\n\n<a title="a lot\n---\nof dashes"/>',
			'<p>`Foo</p>\n<hr />\n<p>`</p>\n<p>&lt;a title=&quot;a lot</p>\n<hr />\n<p>of dashes&quot;/&gt;</p>',
		],
		'092': ['> Foo\n---', '<blockquote>\n<p>Foo</p>\n</blockquote>\n<hr />'],
		'093|deny': ['> foo\n> bar\n> ===', '<blockquote>\n<p>foo\nbar\n===</p>\n</blockquote>'],
		'094': ['- Foo\n---', '<ul>\n<li>Foo</li>\n</ul>\n<hr />'],
		'095|deny': ['Foo\nBar\n---', '<p>Foo\nBar</p>\n<hr />'],
		'096|deny': [
			'---\nFoo\n---\nBar\n---\nBaz',
			'<hr />\n<p>Foo</p>\n<hr />\n<p>Bar</p>\n<hr />\n<p>Baz</p>',
		],
		'097': ['\n====', '<p>====</p>'],
		'098': ['---\n---', '<hr />\n<hr />'],
		'099': ['- foo\n-----', '<ul>\n<li>foo</li>\n</ul>\n<hr />'],
		'100': ['    foo\n---', '<p>foo</p>\n<hr />'],
		'101': ['> foo\n-----', '<blockquote>\n<p>foo</p>\n</blockquote>\n<hr />'],
		'102|deny': ['\\> foo\n-----', '<p>&gt; foo</p>\n<hr />'],
		'103|deny': ['Foo\n\nbar\n---\nbaz', '<p>Foo</p>\n<p>bar</p>\n<hr />\n<p>baz</p>'],
		'104': ['Foo\nbar\n\n---\n\nbaz', '<p>Foo\nbar</p>\n<hr />\n<p>baz</p>'],
		'105': ['Foo\nbar\n* * *\nbaz', '<p>Foo\nbar</p>\n<hr />\n<p>baz</p>'],
		'106': ['Foo\nbar\n\\---\nbaz', '<p>Foo\nbar\n---\nbaz</p>'],
		// @TODO: 107-118 [indented code blocks]
		'119': ['```\n<\n >\n```', '<pre><code>&lt;\n &gt;\n</code></pre>'],
		'120': ['~~~\n<\n >\n~~~', '<pre><code>&lt;\n &gt;\n</code></pre>'],
		'121': ['``\nfoo\n``', '<p><code>foo</code></p>'],
		'122': ['```\naaa\n~~~\n```', '<pre><code>aaa\n~~~\n</code></pre>'],
		'123': ['~~~\naaa\n```\n~~~', '<pre><code>aaa\n```\n</code></pre>'],
		'124': ['````\naaa\n```\n``````', '<pre><code>aaa\n```\n</code></pre>'],
		'125': ['~~~~\naaa\n~~~\n~~~~', '<pre><code>aaa\n~~~\n</code></pre>'],
		'126': ['```', '<pre><code></code></pre>'],
		'127': ['`````\n\n```\naaa', '<pre><code>\n```\naaa\n</code></pre>'],
		'128': [
			'> ````\n> aaa\n\nbbb',
			'<blockquote>\n<pre><code>aaa\n</code></pre>\n</blockquote>\n<p>bbb</p>',
		],
		'129': ['```\n\n  \n```', '<pre><code>\n  \n</code></pre>'],
		'130': ['```\n```', '<pre><code></code></pre>'],
		'131|deny': [' ```\n aaa\naaa\n```', '<pre><code> aaa\naaa\n</code></pre>'],
		'132|deny': ['  ```\naaa\n  aaa\naaa\n  ```', '<pre><code>aaa\n  aaa\naaa\n</code></pre>'],
		'133|deny': [
			'   ```\n   aaa\n    aaa\n  aaa\n   ```',
			'<pre><code>   aaa\n    aaa\n  aaa\n</code></pre>',
		],
		'134|deny': ['    ```\n    aaa\n    ```', '<pre><code>    aaa\n</code></pre>'],
		'135': ['```\naaa\n  ```', '<pre><code>aaa\n</code></pre>'],
		'136': ['   ```\naaa\n  ```', '<pre><code>aaa\n</code></pre>'],
		'137|deny': ['```\naaa\n    ```', '<pre><code>aaa\n</code></pre>'],
		'138': ['``` ```\naaa', '<p><code> </code>\naaa</p>'],
		'139': ['~~~~~~\naaa\n~~~ ~~', '<pre><code>aaa\n~~~ ~~\n</code></pre>'],
		'140': ['foo\n```\nbar\n```\nbaz', '<p>foo</p>\n<pre><code>bar\n</code></pre>\n<p>baz</p>'],
		'141|mod': [
			'foo\n---\n```\nbar\n```\n# baz',
			'<p>foo</p>\n<hr />\n<pre><code>bar\n</code></pre>\n<h1 id="baz">baz</h1>',
		],
		'142|mod': [
			'```ruby\ndef foo(x)\n  return 3\nend\n```',
			'<pre data-language="ruby"><code>def foo(x)\n  return 3\nend\n</code></pre>',
		],
		'143': [
			'```    ruby startline=3 $%@#$\ndef foo(x)\n	return 3\nend\n```',
			'<pre data-language="ruby"><code>def foo(x)\n	return 3\nend\n</code></pre>',
		],
		'144|mod': ['````;\n````', '<pre data-language=";"><code></code></pre>'],
		'145': ['``` aa ```\nfoo', '<p><code>aa</code>\nfoo</p>'],
		'146|mod': ['~~~ aa ``` ~~~\nfoo\n~~~', '<pre data-language="aa"><code>foo\n</code></pre>'],
		'147': ['```\n``` aaa\n```', '<pre><code>``` aaa\n</code></pre>'],
		'148|skip': [
			'<table><tr><td>\n<pre>\n**Hello**,\n\n_world_.\n</pre>\n</td</tr></table>',
			'<table><tr><td>\n<pre>\n**Hello**,\n<p><em>world</em>.\n</pre></p>\n</td></tr></table>',
		],
		'149|skip': [
			'<table>\n  <tr>\n    <td>\n           hi\n    </td>\n  </tr>\n</table>\n\nokay.',
			'<table>\n  <tr>\n    <td>\n           hi\n    </td>\n  </tr>\n</table>\n<p>okay.</p>',
		],
		// @TODO: 150-191 [HTML blocks]
		// @TODO: 192-218 [link reference definitions]
		'219': ['aaa\n\nbbb', '<p>aaa</p>\n<p>bbb</p>'],
		'220': ['aaa\nbbb\n\nccc\nddd', '<p>aaa\nbbb</p>\n<p>ccc\nddd</p>'],
		'221': ['aaa\n\n\nbbb', '<p>aaa</p>\n<p>bbb</p>'],
		'222': ['  aaa\n bbb', '<p>aaa\nbbb</p>'],
		'223': [`aaa\n${' '.repeat(13)}bbb\n${' '.repeat(39)}ccc`, '<p>aaa\nbbb\nccc</p>'],
		'224': ['   aaa\nbbb', '<p>aaa\nbbb</p>'],
		'225|deny': ['    aaa\nbbb', '<p>aaa\nbbb</p>'],
		'226': ['aaa     \nbbb     ', '<p>aaa<br />\nbbb</p>'],
		'227|plus': ['  \n\naaa\n   \n\n# aaa\n\n   ', '<p>aaa</p>\n<h1 id="aaa">aaa</h1>'],
		'228|plus': [
			'> # Foo\n> bar\n> baz',
			'<blockquote>\n<h1 id="foo">Foo</h1>\n<p>bar\nbaz</p>\n</blockquote>',
		],
		'229|plus': [
			'># Foo\n>bar\n> baz',
			'<blockquote>\n<h1 id="foo">Foo</h1>\n<p>bar\nbaz</p>\n</blockquote>',
		],
		'230': [
			'   > # Foo\n   > bar\n > baz',
			'<blockquote>\n<h1 id="foo">Foo</h1>\n<p>bar\nbaz</p>\n</blockquote>',
		],
		'231|deny': [
			'    > # Foo\n    > bar\n    > baz',
			'<blockquote>\n<h1 id="foo">Foo</h1>\n<p>bar\nbaz</p>\n</blockquote>',
		],
		'232|deny': [
			'> # Foo\n> bar\nbaz',
			'<blockquote>\n<h1 id="foo">Foo</h1>\n<p>bar</p>\n</blockquote>\n<p>baz</p>',
		],
		'233|deny': [
			'> bar\nbaz\n> foo',
			'<blockquote>\n<p>bar</p>\n</blockquote>\n<p>baz</p>\n<blockquote>\n<p>foo</p>\n</blockquote>',
		],
		'234': ['> foo\n---', '<blockquote>\n<p>foo</p>\n</blockquote>\n<hr />'],
		'235|deny': [
			'> - foo\n- bar',
			'<blockquote>\n<ul>\n<li>foo</li>\n</ul>\n</blockquote>\n<ul>\n<li>bar</li>\n</ul>',
		],
		'236|deny': ['>     foo\n    bar', '<blockquote>\n<p>foo</p>\n</blockquote>\n<p>bar</p>'],
		'237': [
			'> ```\nfoo\n```',
			'<blockquote>\n<pre><code></code></pre>\n</blockquote>\n<p>foo</p>\n<pre><code></code></pre>',
		],
		'238|deny': [
			'> foo\n    - bar',
			'<blockquote>\n<p>foo</p>\n</blockquote>\n<ul>\n<li>bar</li>\n</ul>',
		],
		'239': ['>', '<blockquote>\n</blockquote>'],
		'240': ['>\n>  \n> ', '<blockquote>\n</blockquote>'],
		'241': ['>\n> foo\n>  ', '<blockquote>\n<p>foo</p>\n</blockquote>'],
		'242': [
			'> foo\n\n> bar',
			'<blockquote>\n<p>foo</p>\n</blockquote>\n<blockquote>\n<p>bar</p>\n</blockquote>',
		],
		'243': ['> foo\n> bar', '<blockquote>\n<p>foo\nbar</p>\n</blockquote>'],
		'244': ['> foo\n>\n> bar', '<blockquote>\n<p>foo</p>\n<p>bar</p>\n</blockquote>'],
		'245': ['foo\n> bar', '<p>foo</p>\n<blockquote>\n<p>bar</p>\n</blockquote>'],
		'246': [
			'> aaa\n***\n> bbb',
			'<blockquote>\n<p>aaa</p>\n</blockquote>\n<hr />\n<blockquote>\n<p>bbb</p>\n</blockquote>',
		],
		'247|deny': ['> bar\nbaz', '<blockquote>\n<p>bar</p>\n</blockquote>\n<p>baz</p>'],
		'248': ['> bar\n\nbaz', '<blockquote>\n<p>bar</p>\n</blockquote>\n<p>baz</p>'],
		'249': ['> bar\n>\nbaz', '<blockquote>\n<p>bar</p>\n</blockquote>\n<p>baz</p>'],
		'250|deny': [
			'> > > foo\nbar',
			'<blockquote>\n<blockquote>\n<blockquote>\n<p>foo</p>\n</blockquote>\n</blockquote>\n</blockquote>\n<p>bar</p>',
		],
		'251|deny': [
			'>>> foo\n> bar\n>>baz',
			'<blockquote>\n<blockquote>\n<blockquote>\n<p>foo</p>\n</blockquote>\n</blockquote>\n<p>bar</p>\n<blockquote>\n<p>baz</p>\n</blockquote>\n</blockquote>',
		],
		'252|deny': ['>     code\n>    not code', '<blockquote>\n<p>code\nnot code</p>\n</blockquote>'],
		'253|deny': [
			'A paragraph\nwith two lines.\n\n    indented code\n\n> A block quote.',
			'<p>A paragraph\nwith two lines.</p>\n<p>indented code</p>\n<blockquote>\n<p>A block quote.</p>\n</blockquote>',
		],
		'254|deny': [
			'1.  A paragraph\n    with two lines.\n\n        indented code\n\n    > A block quote.',
			'<ol>\n<li>\n<p>A paragraph\nwith two lines.</p>\n<p>indented code</p>\n<blockquote>\n<p>A block quote.</p>\n</blockquote>\n</li>\n</ol>',
		],
		'255': ['- one\n\n two', '<ul>\n<li>one</li>\n</ul>\n<p>two</p>'],
		'256': ['- one\n\n  two', '<ul>\n<li>\n<p>one</p>\n<p>two</p>\n</li>\n</ul>'],
		'257|deny': [' -    one\n\n     two', '<ul>\n<li>one</li>\n</ul>\n<p>two</p>'],
		'258': [' -    one\n\n      two', '<ul>\n<li>\n<p>one</p>\n<p>two</p>\n</li>\n</ul>'],
		'259': [
			'   > > 1.  one\n>>\n>>     two',
			'<blockquote>\n<blockquote>\n<ol>\n<li>\n<p>one</p>\n<p>two</p>\n</li>\n</ol>\n</blockquote>\n</blockquote>',
		],
		'260': [
			'>>- one\n>>\n  >  > two',
			'<blockquote>\n<blockquote>\n<ul>\n<li>one</li>\n</ul>\n<p>two</p>\n</blockquote>\n</blockquote>',
		],
		'261': ['-one\n\n2.two', '<p>-one</p>\n<p>2.two</p>'],
		'262': ['- foo\n\n\n  bar', '<ul>\n<li>\n<p>foo</p>\n<p>bar</p>\n</li>\n</ul>'],
		'263': [
			'1.  foo\n\n    ```\n    bar\n    ```\n\n    baz\n\n    > bam',
			'<ol>\n<li>\n<p>foo</p>\n<pre><code>bar\n</code></pre>\n<p>baz</p>\n<blockquote>\n<p>bam</p>\n</blockquote>\n</li>\n</ol>',
		],
		'264|deny': [
			'- Foo\n\n      bar\n\n\n      baz',
			'<ul>\n<li>\n<p>Foo</p>\n<p>bar</p>\n<p>baz</p>\n</li>\n</ul>',
		],
		'265': ['123456789. ok', '<ol start="123456789">\n<li>ok</li>\n</ol>'],
		'266': ['1234567890. not ok', '<p>1234567890. not ok</p>'],
		'267': ['0. ok', '<ol start="0">\n<li>ok</li>\n</ol>'],
		'268': ['003. ok', '<ol start="3">\n<li>ok</li>\n</ol>'],
		'269': ['-1. not ok', '<p>-1. not ok</p>'],
		'270|deny': ['- foo\n\n      bar', '<ul>\n<li>\n<p>foo</p>\n<p>bar</p>\n</li>\n</ul>'],
		'271|deny': [
			'  10.  foo\n\n           bar',
			'<ol start="10">\n<li>\n<p>foo</p>\n<p>bar</p>\n</li>\n</ol>',
		],
		'272|deny': [
			'    indented code\n\nparagraph\n\n    more code',
			'<p>indented code</p>\n<p>paragraph</p>\n<p>more code</p>',
		],
		'273|deny': [
			'1.     indented code\n\n   paragraph\n\n       more code',
			'<ol>\n<li>indented code</li>\n</ol>\n<p>paragraph</p>\n<p>more code</p>',
		],
		'274|deny': [
			'1.      indented code\n\n   paragraph\n\n       more code',
			'<ol>\n<li>indented code</li>\n</ol>\n<p>paragraph</p>\n<p>more code</p>',
		],
		'275': ['   foo\n\nbar', '<p>foo</p>\n<p>bar</p>'],
		'276': ['-    foo\n\n  bar', '<ul>\n<li>foo</li>\n</ul>\n<p>bar</p>'],
		'277': ['-  foo\n\n   bar', '<ul>\n<li>\n<p>foo</p>\n<p>bar</p>\n</li>\n</ul>'],
		'278|todo': [
			'-\n  foo\n-\n  ```\n  bar\n  ```\n-\n      baz',
			'<ul>\n<li>foo</li>\n<li>\n<pre><code>bar\n</code></pre>\n</li>\n<li>baz</li>\n</ul>',
		],
		'279|todo': ['-   \n  foo', '<ul>\n<li></li>\n</ul>\n<p>foo</p>'],
		'280|todo': ['-\n\n  foo', '<ul>\n<li></li>\n</ul>\n<p>foo</p>'],
		'281': ['- foo\n-\n- bar', '<ul>\n<li>foo</li>\n<li></li>\n<li>bar</li>\n</ul>'],
		'282': ['- foo\n-   \n- bar', '<ul>\n<li>foo</li>\n<li></li>\n<li>bar</li>\n</ul>'],
		'283': ['1. foo\n2.\n3. bar', '<ol>\n<li>foo</li>\n<li></li>\n<li>bar</li>\n</ol>'],
		'284': ['*', '<ul>\n<li></li>\n</ul>'],
		// @TODO: 285-300 [list items]
		// @TODO: 301-326 [lists]
		'327': ['`hi`lo`', '<p><code>hi</code>lo`</p>'],
		'328': ['`code`', '<p><code>code</code></p>'],
		'329': ['`` code with `backticks ``', '<p><code>code with `backticks</code></p>'],
		'330': ['` `` `', '<p><code>``</code></p>'],
		'331': ['`  ``  `', '<p><code> `` </code></p>'],
		'332': ['` a`', '<p><code> a</code></p>'],
		'333': ['` b `', '<p><code> b </code></p>'],
		'334': ['` `\n`  `', '<p><code> </code>\n<code>  </code></p>'],
		'335': ['``\nfoo\nbar  \nbaz\n``', '<p><code>foo bar   baz</code></p>'],
		'336': ['``\nfoo \n``', '<p><code>foo </code></p>'],
		'337': ['`foo   bar \nbaz`', '<p><code>foo   bar  baz</code></p>'],
		'338': ['`foo\\`bar`', '<p><code>foo\\</code>bar`</p>'],
		'339': ['``foo`bar``', '<p><code>foo`bar</code></p>'],
		'340': ['` foo `` bar `', '<p><code>foo `` bar</code></p>'],
		'341': ['*foo`*`', '<p>*foo<code>*</code></p>'],
		'342': ['[not a `link](/foo`)', '<p>[not a <code>link](/foo</code>)</p>'],
		'343': ['`<a href="`">`', '<p><code>&lt;a href=&quot;</code>&quot;&gt;`</p>'],
		'344|todo': ['<a href="`">`', '<p><a href="`">`</p>'],
		'345': ['`<https://foo.bar.`baz>`', '<p><code>&lt;https://foo.bar.</code>baz&gt;`</p>'],
		'346': [
			'<https://foo.bar.`baz>`',
			'<p><a href="https://foo.bar.%60baz">https://foo.bar.`baz</a>`</p>',
		],
		'347': ['```foo``', '<p>```foo``</p>'],
		'348': ['`foo', '<p>`foo</p>'],
		'349': ['`foo``bar``', '<p>`foo<code>bar</code></p>'],
		'350': ['*foo bar*', '<p><em>foo bar</em></p>'],
		'351': ['a * foo bar*', '<p>a * foo bar*</p>'],
		'352': ['a*"foo"*', '<p>a*&quot;foo&quot;*</p>'],
		'353': ['* a *', '<p>* a *</p>'],
		'354': [
			'*$*alpha.\n\n*£*bravo.\n\n*€*charlie.',
			'<p>*$*alpha.</p>\n<p>*£*bravo.</p>\n<p>*€*charlie.</p>',
		],
		'355': ['foo*bar*', '<p>foo<em>bar</em></p>'],
		'356': ['5*6*78', '<p>5<em>6</em>78</p>'],
		'358': ['_ foo bar_', '<p>_ foo bar_</p>'],
		'359': ['a_"foo"_', '<p>a_&quot;foo&quot;_</p>'],
		'360': ['foo_bar_', '<p>foo_bar_</p>'],
		'361': ['5_6_78', '<p>5_6_78</p>'],
		'362': ['пристаням_стремятся_', '<p>пристаням_стремятся_</p>'],
		'363': ['aa_"bb"_cc', '<p>aa_&quot;bb&quot;_cc</p>'],
		'364': ['foo-_(bar)_', '<p>foo-<em>(bar)</em></p>'],
		'365': ['_foo*', '<p>_foo*</p>'],
		'366': ['*foo bar *', '<p>*foo bar *</p>'],
		'367': ['*foo bar\n*', '<p>*foo bar\n*</p>'],
		'368': ['*(*foo)', '<p>*(*foo)</p>'],
		'369': ['*(*foo*)*', '<p><em>(<em>foo</em>)</em></p>'],
		'370': ['*foo*bar', '<p><em>foo</em>bar</p>'],
		'371': ['_foo bar _', '<p>_foo bar _</p>'],
		'372': ['_(_foo)', '<p>_(_foo)</p>'],
		'373': ['_(_foo_)_', '<p><em>(<em>foo</em>)</em></p>'],
		'374': ['_foo_bar', '<p>_foo_bar</p>'],
		'375': ['_пристаням_стремятся', '<p>_пристаням_стремятся</p>'],
		'376': ['_foo_bar_baz_', '<p><em>foo_bar_baz</em></p>'],
		'377': ['_(bar)_.', '<p><em>(bar)</em>.</p>'],
		'378': ['**foo bar**', '<p><strong>foo bar</strong></p>'],
		'379': ['** foo bar**', '<p>** foo bar**</p>'],
		'380': ['a**"foo"**', '<p>a**&quot;foo&quot;**</p>'],
		'381': ['foo**bar**', '<p>foo<strong>bar</strong></p>'],
		'382': ['__foo bar__', '<p><strong>foo bar</strong></p>'],
		'383': ['__ foo bar__', '<p>__ foo bar__</p>'],
		'384': ['__\nfoo bar__', '<p>__\nfoo bar__</p>'],
		'385': ['a__"foo"__', '<p>a__&quot;foo&quot;__</p>'],
		'386': ['foo__bar__', '<p>foo__bar__</p>'],
		'387': ['5__6__78', '<p>5__6__78</p>'],
		'388': ['пристаням__стремятся__', '<p>пристаням__стремятся__</p>'],
		'389': ['__foo, __bar__, baz__', '<p><strong>foo, <strong>bar</strong>, baz</strong></p>'],
		'390': ['foo-__(bar)__', '<p>foo-<strong>(bar)</strong></p>'],
		'391': ['**foo bar **', '<p>**foo bar **</p>'],
		'392': ['**(**foo)', '<p>**(**foo)</p>'],
		'393': ['*(**foo**)*', '<p><em>(<strong>foo</strong>)</em></p>'],
		'394': [
			'**Gomphocarpus (*Gomphocarpus physocarpus*, syn.\n*Asclepias physocarpa*)**',
			'<p><strong>Gomphocarpus (<em>Gomphocarpus physocarpus</em>, syn.\n<em>Asclepias physocarpa</em>)</strong></p>',
		],
		'395': ['**foo "*bar*" foo**', '<p><strong>foo &quot;<em>bar</em>&quot; foo</strong></p>'],
		'396': ['**foo**bar', '<p><strong>foo</strong>bar</p>'],
		'397': ['__foo bar __', '<p>__foo bar __</p>'],
		'398': ['__(__foo)', '<p>__(__foo)</p>'],
		'399': ['_(__foo__)_', '<p><em>(<strong>foo</strong>)</em></p>'],
		'400': ['__foo__bar', '<p>__foo__bar</p>'],
		'401': ['__пристаням__стремятся', '<p>__пристаням__стремятся</p>'],
		'402': ['__foo__bar__baz__', '<p><strong>foo__bar__baz</strong></p>'],
		'403': ['__(bar)__.', '<p><strong>(bar)</strong>.</p>'],
		'404': ['*foo [bar](/url)*', '<p><em>foo <a href="/url">bar</a></em></p>'],
		'405': ['*foo\nbar*', '<p><em>foo\nbar</em></p>'],
		'406': ['_foo __bar__ baz_', '<p><em>foo <strong>bar</strong> baz</em></p>'],
		'407': ['_foo _bar_ baz_', '<p><em>foo <em>bar</em> baz</em></p>'],
		'408': ['__foo_ bar_', '<p><em><em>foo</em> bar</em></p>'],
		'409': ['*foo *bar**', '<p><em>foo <em>bar</em></em></p>'],
		'410': ['*foo **bar** baz*', '<p><em>foo <strong>bar</strong> baz</em></p>'],
		'411': ['*foo**bar**baz*', '<p><em>foo<strong>bar</strong>baz</em></p>'],
		'412': ['*foo**bar*', '<p><em>foo**bar</em></p>'],
		'413': ['***foo** bar*', '<p><em><strong>foo</strong> bar</em></p>'],
		'414': ['*foo **bar***', '<p><em>foo <strong>bar</strong></em></p>'],
		'415': ['*foo**bar***', '<p><em>foo<strong>bar</strong></em></p>'],
		'416|todo': ['foo***bar***baz', '<p>foo<em><strong>bar</strong></em>baz</p>'],
		'417|todo': [
			'foo******bar*********baz',
			'<p>foo<strong><strong><strong>bar</strong></strong></strong>***baz</p>',
		],
		'418': [
			'*foo **bar *baz* bim** bop*',
			'<p><em>foo <strong>bar <em>baz</em> bim</strong> bop</em></p>',
		],
		'419': ['*foo [*bar*](/url)*', '<p><em>foo <a href="/url"><em>bar</em></a></em></p>'],
		'420': ['** is not an empty emphasis', '<p>** is not an empty emphasis</p>'],
		'421': ['**** is not an empty strong emphasis', '<p>**** is not an empty strong emphasis</p>'],
		'422': ['**foo [bar](/url)**', '<p><strong>foo <a href="/url">bar</a></strong></p>'],
		'423': ['**foo\nbar**', '<p><strong>foo\nbar</strong></p>'],
		'424': ['__foo _bar_ baz__', '<p><strong>foo <em>bar</em> baz</strong></p>'],
		'425': ['__foo __bar__ baz__', '<p><strong>foo <strong>bar</strong> baz</strong></p>'],
		'426': ['____foo__ bar__', '<p><strong><strong>foo</strong> bar</strong></p>'],
		'427': ['**foo **bar****', '<p><strong>foo <strong>bar</strong></strong></p>'],
		'428': ['**foo *bar* baz**', '<p><strong>foo <em>bar</em> baz</strong></p>'],
		'429': ['**foo*bar*baz**', '<p><strong>foo<em>bar</em>baz</strong></p>'],
		'430': ['***foo* bar**', '<p><strong><em>foo</em> bar</strong></p>'],
		'431': ['**foo *bar***', '<p><strong>foo <em>bar</em></strong></p>'],
		'432': [
			'**foo *bar **baz**\nbim* bop**',
			'<p><strong>foo <em>bar <strong>baz</strong>\nbim</em> bop</strong></p>',
		],
		'433': ['**foo [*bar*](/url)**', '<p><strong>foo <a href="/url"><em>bar</em></a></strong></p>'],
		'434': ['__ is not an empty emphasis', '<p>__ is not an empty emphasis</p>'],
		'435': ['____ is not an empty strong emphasis', '<p>____ is not an empty strong emphasis</p>'],
		'436': ['foo ***', '<p>foo ***</p>'],
		'437': ['foo *\\**', '<p>foo <em>*</em></p>'],
		'438': ['foo *_*', '<p>foo <em>_</em></p>'],
		'439': ['foo *****', '<p>foo *****</p>'],
		'440': ['foo **\\***', '<p>foo <strong>*</strong></p>'],
		'441': ['foo **_**', '<p>foo <strong>_</strong></p>'],
		'442': ['**foo*', '<p>*<em>foo</em></p>'],
		'443': ['*foo**', '<p><em>foo</em>*</p>'],
		'444': ['***foo**', '<p>*<strong>foo</strong></p>'],
		'445': ['****foo*', '<p>***<em>foo</em></p>'],
		'446': ['**foo***', '<p><strong>foo</strong>*</p>'],
		'447': ['*foo****', '<p><em>foo</em>***</p>'],
		'448': ['foo ___', '<p>foo ___</p>'],
		'449': ['foo _\\__', '<p>foo <em>_</em></p>'],
		'450': ['foo _*_', '<p>foo <em>*</em></p>'],
		'451': ['foo _____', '<p>foo _____</p>'],
		'452': ['foo __\\___', '<p>foo <strong>_</strong></p>'],
		'453': ['foo __*__', '<p>foo <strong>*</strong></p>'],
		'454': ['__foo_', '<p>_<em>foo</em></p>'],
		'455': ['_foo__', '<p><em>foo</em>_</p>'],
		'456': ['___foo__', '<p>_<strong>foo</strong></p>'],
		'457': ['____foo_', '<p>___<em>foo</em></p>'],
		'458': ['__foo___', '<p><strong>foo</strong>_</p>'],
		'459': ['_foo____', '<p><em>foo</em>___</p>'],
		'460': ['**foo**', '<p><strong>foo</strong></p>'],
		'461': ['*_foo_*', '<p><em><em>foo</em></em></p>'],
		'462': ['__foo__', '<p><strong>foo</strong></p>'],
		'463': ['_*foo*_', '<p><em><em>foo</em></em></p>'],
		'464': ['****foo****', '<p><strong><strong>foo</strong></strong></p>'],
		'465': ['____foo____', '<p><strong><strong>foo</strong></strong></p>'],
		'466': ['******foo******', '<p><strong><strong><strong>foo</strong></strong></strong></p>'],
		'467': ['***foo***', '<p><em><strong>foo</strong></em></p>'],
		'468': ['_____foo_____', '<p><em><strong><strong>foo</strong></strong></em></p>'],
		'469|todo': ['*foo _bar* baz_', '<p><em>foo _bar</em> baz_</p>'],
		'470|todo': [
			'*foo __bar *baz bim__ bam*',
			'<p><em>foo <strong>bar *baz bim</strong> bam</em></p>',
		],
		'471': ['**foo **bar baz**', '<p>**foo <strong>bar baz</strong></p>'],
		'472': ['*foo *bar baz*', '<p>*foo <em>bar baz</em></p>'],
		'473': ['*[bar*](/url)', '<p>*<a href="/url">bar*</a></p>'],
		'474': ['_foo [bar_](/url)', '<p>_foo <a href="/url">bar_</a></p>'],
		'475|todo': ['*<img src="foo" title="*"/>', '<p>*<img src="foo" title="*"/></p>'],
		'476|todo': ['**<a href="**">', '<p>**<a href="**"></p>'],
		'477|todo': ['__<a href="__">', '<p>__<a href="__"></p>'],
		'478': ['*a `*`*', '<p><em>a <code>*</code></em></p>'],
		'479': ['_a `_`_', '<p><em>a <code>_</code></em></p>'],
		'480': [
			'**a<https://foo.bar/?q=**>',
			'<p>**a<a href="https://foo.bar/?q=**">https://foo.bar/?q=**</a></p>',
		],
		'481': [
			'__a<https://foo.bar/?q=__>',
			'<p>__a<a href="https://foo.bar/?q=__">https://foo.bar/?q=__</a></p>',
		],
		'482': ['[link](/uri "title")', '<p><a href="/uri" title="title">link</a></p>'],
		'483': ['[link](/uri)', '<p><a href="/uri">link</a></p>'],
		'484': ['[](./target.md)', '<p><a href="./target.md"></a></p>'],
		'485': ['[link]()', '<p><a href="">link</a></p>'],
		'486': ['[link](<>)', '<p><a href="">link</a></p>'],
		'487': ['[]()', '<p><a href=""></a></p>'],
		'488': ['[link](/my uri)', '<p>[link](/my uri)</p>'],
		'489': ['[link](</my uri>)', '<p><a href="/my%20uri">link</a></p>'],
		'490': ['[link](foo\nbar)', '<p>[link](foo\nbar)</p>'],
		'491|todo': ['[link](<foo\nbar>)', '<p>[link](<foo\nbar>)</p>'],
		'492': ['[a](<b)c>)', '<p><a href="b)c">a</a></p>'],
		'493': ['[link](<foo\\>)', '<p>[link](&lt;foo&gt;)</p>'],
		'494|todo': [
			'[a](<b)c\n[a](<b)c>\n[a](<b>c)',
			'<p>[a](&lt;b)c\n[a](&lt;b)c&gt;\n[a](<b>c)</p>',
		],
		'495|todo': ['[link](\\(foo\\))', '<p><a href="(foo)">link</a></p>'],
		// @TODO: 496-571 [links]
		'572|mod': ['a ![foo](/url "title")', '<p>a <img src="/url" alt="foo" title="title" /></p>'],
		'573|skip': [
			'![foo *bar*]\n\n[foo *bar*]: train.jpg "train & tracks"',
			'<p><img src="train.jpg" alt="foo bar" title="train &amp; tracks" /></p>',
		],
		'574|todo': ['a ![foo ![bar](/url)](/url2)', '<p>a <img src="/url2" alt="foo bar" /></p>'],
		'575|todo': ['a ![foo [bar](/url)](/url2)', '<p>a <img src="/url2" alt="foo bar" /></p>'],
		// @TODO: 576-593 [images]
		// @TODO: 594-612 [auto links]
		// @TODO: 613-632 [raw html]
		'633': ['foo  \nbaz', '<p>foo<br />\nbaz</p>'],
		'634': ['foo\\\nbaz', '<p>foo<br />\nbaz</p>'],
		'635': ['foo       \nbaz', '<p>foo<br />\nbaz</p>'],
		'636': ['foo  \n     bar', '<p>foo<br />\nbar</p>'],
		'637': ['foo\\\n     bar', '<p>foo<br />\nbar</p>'],
		'638': ['*foo  \nbar*', '<p><em>foo<br />\nbar</em></p>'],
		'639': ['*foo\\\nbar*', '<p><em>foo<br />\nbar</em></p>'],
		'640': ['`code  \nspan`', '<p><code>code   span</code></p>'],
		'641': ['`code\\\nspan`', '<p><code>code\\ span</code></p>'],
		'642|skip': ['<a href="foo  \nbar">', '<a href="foo  \nbar">'],
		'643|skip': ['<a href="foo\\\nbar">', '<a href="foo\\\nbar">'],
		'644': ['foo\\', '<p>foo\\</p>'],
		'645': ['foo  ', '<p>foo</p>'],
		'646|plus': ['### foo\\', '<h3 id="foo">foo\\</h3>'],
		'647|plus': ['### foo  ', '<h3 id="foo">foo</h3>'],
		'648': ['foo\nbaz', '<p>foo\nbaz</p>'],
		'649': ['foo \n baz', '<p>foo\nbaz</p>'],
		'650': ["hello $.;'there", "<p>hello $.;'there</p>"],
		'651': ['Foo χρῆν', '<p>Foo χρῆν</p>'],
		'652': ['Multiple     spaces', '<p>Multiple     spaces</p>'],
		// that's all the examples from the spec!
	};

	const mark = forge();
	for (const test in suite) {
		const [input, output] = suite[test];
		const [, ...props] = test.split('|');
		const options: Parameters<typeof it>[1] = {
			fails: props.includes('fail'),
			only: props.includes('only'),
			skip: props.includes('skip'),
			todo: props.includes('todo'),
		};
		it(test, options, ({ expect }) => {
			expect(mark(input).html()).toBe(output);
		});
	}
});

describe('libretto', ({ concurrent: it }) => {
	const suite: Record<string, [string, string]> = {
		'crlf#paragraph': ['aaa\r\n\r\nbbb', '<p>aaa</p>\n<p>bbb</p>'],

		'comment#block/1': ['<!-- comment -->', ''],
		'comment#block/2': ['<!---\ncomment\n--->', ''],
		'comment#block/3': ['<!-- comment with -- is fine -->', ''],
		'comment#inline/1': ['a <!-- comment --> b', '<p>a  b</p>'],
		'comment#inline/2': ['a <!-- comment --> b -->', '<p>a  b –&gt;</p>'],
		'comment#inline/3': ['a <!-- comment b', '<p>a &lt;!– comment b</p>'],

		'directive#youtube': [
			'@youtube{id=7TovqLDCosk caption="hitoribocchi tokyo"}',
			[
				'<figure>',
				'<div data-aubade="youtube">',
				'<iframe src="https://www.youtube-nocookie.com/embed/7TovqLDCosk" title="YouTube video player" loading="lazy" frameborder="0" allowfullscreen allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin"></iframe>',
				'</div>',
				'<figcaption>hitoribocchi tokyo</figcaption>',
				'</figure>',
			].join('\n'),
		],
		'directive#youtube/disclosure': [
			'@youtube{disclosure id=7TovqLDCosk caption="hitoribocchi tokyo"}',
			[
				'<details>',
				'<summary>hitoribocchi tokyo</summary>',
				'<div data-aubade="youtube">',
				'<iframe src="https://www.youtube-nocookie.com/embed/7TovqLDCosk" title="YouTube video player" loading="lazy" frameborder="0" allowfullscreen allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin"></iframe>',
				'</div>',
				'</details>',
			].join('\n'),
		],
		'directive#youtube/newlines': [
			['@youtube{', '  id=7TovqLDCosk', '  caption="hitoribocchi tokyo"', '}'].join('\n'),
			[
				'<figure>',
				'<div data-aubade="youtube">',
				'<iframe src="https://www.youtube-nocookie.com/embed/7TovqLDCosk" title="YouTube video player" loading="lazy" frameborder="0" allowfullscreen allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin"></iframe>',
				'</div>',
				'<figcaption>hitoribocchi tokyo</figcaption>',
				'</figure>',
			].join('\n'),
		],
		'directive#youtube/no-caption': [
			'@youtube{id=7TovqLDCosk}',
			[
				'<figure>',
				'<div data-aubade="youtube">',
				'<iframe src="https://www.youtube-nocookie.com/embed/7TovqLDCosk" title="YouTube video player" loading="lazy" frameborder="0" allowfullscreen allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin"></iframe>',
				'</div>',
				'</figure>',
			].join('\n'),
		],
		'directive#youtube/series': [
			'@youtube{series="PLZRRxQcaEjA4qyEuYfAMCazlL0vQDkIj2" caption="Mind Field: Season 1"}',
			[
				'<figure>',
				'<div data-aubade="youtube">',
				'<iframe src="https://www.youtube-nocookie.com/embed/videoseries?list=PLZRRxQcaEjA4qyEuYfAMCazlL0vQDkIj2" title="YouTube video player" loading="lazy" frameborder="0" allowfullscreen allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin"></iframe>',
				'</div>',
				'<figcaption>Mind Field: Season 1</figcaption>',
				'</figure>',
			].join('\n'),
		],

		'directive#video': [
			'@video{src="./video.mp4" caption="local video"}',
			[
				'<figure>',
				'<div data-aubade="video">',
				'<video controls preload="metadata">',
				'<source src="./video.mp4" type="video/mp4" />',
				'Your browser does not support HTML5 video.',
				'</video>',
				'</div>',
				'<figcaption>local video</figcaption>',
				'</figure>',
			].join('\n'),
		],
		'directive#video/disclosure': [
			'@video{disclosure src="./video.mp4" caption="local video"}',
			[
				'<details>',
				'<summary>local video</summary>',
				'<div data-aubade="video">',
				'<video controls preload="metadata">',
				'<source src="./video.mp4" type="video/mp4" />',
				'Your browser does not support HTML5 video.',
				'</video>',
				'</div>',
				'</details>',
			].join('\n'),
		],
		'directive#video/no-caption': [
			'@video{src="./video.mp4"}',
			[
				'<figure>',
				'<div data-aubade="video">',
				'<video controls preload="metadata">',
				'<source src="./video.mp4" type="video/mp4" />',
				'Your browser does not support HTML5 video.',
				'</video>',
				'</div>',
				'</figure>',
			].join('\n'),
		],

		'image#plain': [
			'![unannotated *alt* text](img.png)',
			[
				'<figure>',
				'<div data-aubade="image">',
				'<img src="img.png" alt="unannotated *alt* text" />',
				'</div>',
				'</figure>',
			].join('\n'),
		],
		'image#caption': [
			'![alt](img.png "annotated *title* for caption")',
			[
				'<figure>',
				'<div data-aubade="image">',
				'<img src="img.png" alt="alt" />',
				'</div>',
				'<figcaption>annotated <em>title</em> for caption</figcaption>',
				'</figure>',
			].join('\n'),
		],

		'quotes#escaped': ['\\"a b\\"', '<p>&quot;a b&quot;</p>'],
		'quotes#double/1': ['"hello"', '<p>“hello”</p>'],
		'quotes#double/2': ['"a *b* c"', '<p>“a <em>b</em> c”</p>'],
		'quotes#double/3': ['"(quote)"', '<p>“(quote)”</p>'],
		'quotes#single/1': ["'hello'", '<p>‘hello’</p>'],
		'quotes#single/2': ["'a 'b' c'", '<p>‘a ‘b’ c’</p>'],
		'quotes#single/3': ["don't", '<p>don’t</p>'],
		'quotes#prime/1': ['24" monitor', '<p>24″ monitor</p>'],
		'quotes#prime/2': [`5'5"`, '<p>5′5″</p>'],
		'quotes#mixed/1': [`"a 'b' c"`, '<p>“a ‘b’ c”</p>'],
		'quotes#mixed/2': [`'a "b" c'`, '<p>‘a “b” c’</p>'],
		'quotes#mixed/3': [`'a "b' c"`, '<p>‘a “b’ c”</p>'],
		'quotes#mixed/4': [`'"hello"'`, '<p>‘“hello”’</p>'],
		'quotes#mixed/5': [`"'hello'"`, '<p>“‘hello’”</p>'],
		'quotes#mixed/6': [`"i'm sure"`, '<p>“i’m sure”</p>'],
		'quotes#mixed/7': [`"13" laptop"`, '<p>“13″ laptop”</p>'],

		'strike#single': ['~strike~', '<p>~strike~</p>'],
		'strike#normal': ['~~strike~~', '<p><del>strike</del></p>'],
		'strike#code/1': ['~~`a~~`', '<p>~~<code>a~~</code></p>'],
		'strike#code/2': ['`~~a`~~', '<p><code>~~a</code>~~</p>'],
		'strike#links/1': ['[~~a](/url)~~', '<p><a href="/url">~~a</a>~~</p>'],
		'strike#links/2': ['~~[a~~](/url)', '<p>~~<a href="/url">a~~</a></p>'],
		'strike#links/3': ['[~~a~~](/url)', '<p><a href="/url"><del>a</del></a></p>'],
		'strike#nested/1|todo': ['x ~~~~y~~~~', '<p>x <del><del>y</del></del></p>'],
		'strike#nested/2|todo': ['x ~~~~y~~ z~~', '<p>x <del><del>y</del> z</del></p>'],
		'strike#nested/3': ['x ~~y ~~z~~~~', '<p>x <del>y <del>z</del></del></p>'],
		'strike#nested/4|todo': [
			'x ~~a ~~y~~~~~~~~~~~z~~ b~~',
			'<p>x <del>a <del>y</del></del>~~~<del><del>z</del> b</del></p>',
		],
		'strike#nested/5|todo': [
			'x ~~a ~~y~~~~~~~~~~~~z~~ b~~',
			'<p>x <del>a <del>y</del></del>~~~~<del><del>z</del> b</del></p>',
		],
		'strike#nested/6': ['~~a ~~b~~ c~~', '<p><del>a <del>b</del> c</del></p>'],
		'strike#mixed/1|todo': ['**~~a**~~', '<p><strong>~~a</strong>~~</p>'],
		'strike#mixed/2|todo': ['~~**a~~**', '<p><del>**a</del>**</p>'],
		'strike#mixed/3': [
			'~~a **b ~~c d~~ e** f~~',
			'<p><del>a <strong>b <del>c d</del> e</strong> f</del></p>',
		],
		'strike#invalid': ['a ~~ b ~~ c', '<p>a ~~ b ~~ c</p>'],
		'strike#newline/1': ['~~a\n~~', '<p>~~a\n~~</p>'],
		'strike#newline/2': ['~~\na~~', '<p>~~\na~~</p>'],
		'strike#newline/3': ['~~\na\n~~', '<p>~~\na\n~~</p>'],
		'strike#between/1': ['a~~"b"~~', '<p>a~~“b”~~</p>'],
		'strike#between/2|todo': ['-~~~~;~~~~~~', '<p>-<del><del>;</del></del>~~</p>'],

		'table#normal': [
			'| a | b |\n| --- | --- |\n| c | d |',
			'<table>\n<thead>\n<tr>\n<th>a</th>\n<th>b</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>c</td>\n<td>d</td>\n</tr>\n</tbody>\n</table>',
		],
		'table#piped': [
			'| a\\|bc  |\n| ------ |\n| d `\\|` ef |\n| g **\\|** hi |',
			'<table>\n<thead>\n<tr>\n<th>a|bc</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>d <code>|</code> ef</td>\n</tr>\n<tr>\n<td>g <strong>|</strong> hi</td>\n</tr>\n</tbody>\n</table>',
		],
	};

	for (const test in suite) {
		const [input, output] = suite[test];
		const [, ...props] = test.split('|');
		const options: Parameters<typeof it>[1] = {
			fails: props.includes('fail'),
			only: props.includes('only'),
			skip: props.includes('skip'),
			todo: props.includes('todo'),
		};
		it(test, options, ({ expect }) => {
			expect(engrave(input).html()).toBe(output);
		});
	}
});
